import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { buildDesignBundles } from './build-design.mjs';

const root = resolve('.');
const designDir = resolve(root, 'design');
const exportDir = resolve(designDir, 'export');

const designPages = [
  'index.html',
  'launcher-current-view.html',
  'settings-current-view.html',
  'settings-current-view2.html',
  'settings-current-view3.html'
];

function stripSourceMapComment(source) {
  return source.replace(/\n\/\/# sourceMappingURL=.*\n?$/u, '\n');
}

async function inlinePage(pageName) {
  const sourcePath = resolve(designDir, pageName);
  const sourceDir = dirname(sourcePath);
  const originalHtml = await readFile(sourcePath, 'utf8');

  if (pageName === 'index.html') {
    return `<!-- Generated by npm run export:design. Do not edit by hand. -->\n${originalHtml}`;
  }

  const styleHrefs = [...originalHtml.matchAll(/<link rel="stylesheet" href="([^"]+)" \/>/gu)].map((match) => match[1]);
  const inlinedStyles = await Promise.all(
    styleHrefs.map(async (href) => {
      const cssPath = resolve(sourceDir, href);
      return readFile(cssPath, 'utf8');
    })
  );

  const bundleMatch = originalHtml.match(/script\.src = '([^']+\.js)';/u);
  const bundleSource = bundleMatch
    ? stripSourceMapComment(await readFile(resolve(sourceDir, bundleMatch[1]), 'utf8'))
    : null;

  const title = originalHtml.match(/<title>([^<]+)<\/title>/u)?.[1] ?? 'Northlight Design Export';
  const bodyAttributes = originalHtml.match(/<body([^>]*)>/u)?.[1] ?? '';
  const headerTitle = originalHtml.match(/<div class="title">([^<]+)<\/div>/u)?.[1] ?? '';
  const headerNote = originalHtml.match(/<div class="note">([^<]+)<\/div>/u)?.[1] ?? '';
  const designShell = originalHtml.match(/data-design-shell="([^"]+)"/u)?.[1] ?? 'launcher';
  const mainTitle = originalHtml.match(/<main class="frame"[^>]*title="([^"]+)"/u)?.[1] ?? title;

  return `<!-- Generated by npm run export:design. Do not edit by hand. -->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
${inlinedStyles.map((css) => `    <style>\n${css}\n    </style>`).join('\n')}
  </head>
  <body${bodyAttributes}>
    <header class="meta" data-design-shell="${designShell}">
      <div class="title">${headerTitle}</div>
      <div class="note">${headerNote}</div>
    </header>
    <main class="frame" data-design-shell="${designShell}" title="${mainTitle}">
      <div id="root"></div>
    </main>
${bundleSource ? `    <script>\n${bundleSource}\n    </script>\n` : ''}  </body>
</html>
`;
}

export async function exportDesignPages() {
  await buildDesignBundles();
  await mkdir(exportDir, { recursive: true });

  for (const pageName of designPages) {
    const exportHtml = await inlinePage(pageName);
    await writeFile(resolve(exportDir, pageName), exportHtml, 'utf8');
  }
}

await exportDesignPages();
